/**
 * Zod Schemas & Lightweight Standalone Validator for Codex Computer Use Tools (Windows Version)
 * Extracted from app-initial / module 1094 & main-g2764IDy.js
 */

let z;
try {
  const zodModule = await import("zod");
  z = zodModule.z;
} catch {
  // Built-in lightweight Zod-compatible fallback for zero-dependency execution
  class Schema {
    constructor(validator) {
      this._validator = validator;
      this._description = "";
    }
    describe(d) {
      this._description = d;
      return this;
    }
    optional() {
      return new Schema((val) => (val === undefined ? { success: true, data: undefined } : this._validator(val)));
    }
    catch(fallback) {
      return new Schema((val) => {
        const res = this._validator(val);
        return res.success ? res : { success: true, data: fallback };
      });
    }
    default(fallback) {
      return new Schema((val) => (val === undefined ? { success: true, data: fallback } : this._validator(val)));
    }
    transform(fn) {
      return new Schema((val) => {
        const res = this._validator(val);
        return res.success ? { success: true, data: fn(res.data) } : res;
      });
    }
    pipe(next) {
      return new Schema((val) => {
        const res = this._validator(val);
        return res.success ? next.safeParse(res.data) : res;
      });
    }
    passthrough() { return this; }
    min() { return this; }
    max() { return this; }
    positive() { return this; }
    int() { return this; }
    nonnegative() { return this; }
    safeParse(val) {
      return this._validator(val);
    }
    parse(val) {
      const res = this.safeParse(val);
      if (!res.success) throw new Error(res.error?.message || "Validation error");
      return res.data;
    }
  }

  z = {
    string: () => new Schema((v) => typeof v === "string" ? { success: true, data: v } : { success: false, error: { message: "Expected string" } }),
    number: () => new Schema((v) => typeof v === "number" && !isNaN(v) ? { success: true, data: v } : { success: false, error: { message: "Expected number" } }),
    boolean: () => new Schema((v) => typeof v === "boolean" ? { success: true, data: v } : { success: false, error: { message: "Expected boolean" } }),
    any: () => new Schema((v) => ({ success: true, data: v })),
    enum: (values) => new Schema((v) => values.includes(v) ? { success: true, data: v } : { success: false, error: { message: `Expected one of ${values.join(", ")}` } }),
    tuple: (schemas) => new Schema((v) => {
      if (!Array.isArray(v) || v.length !== schemas.length) return { success: false, error: { message: "Tuple length mismatch" } };
      const data = [];
      for (let i = 0; i < schemas.length; i++) {
        const res = schemas[i].safeParse(v[i]);
        if (!res.success) return res;
        data.push(res.data);
      }
      return { success: true, data };
    }),
    union: (schemas) => new Schema((v) => {
      for (const s of schemas) {
        const res = s.safeParse(v);
        if (res.success) return res;
      }
      return { success: false, error: { message: "Union validation failed" } };
    }),
    object: (shape) => new Schema((v) => {
      if (typeof v !== "object" || v === null) return { success: false, error: { message: "Expected object" } };
      const data = { ...v };
      for (const key of Object.keys(shape)) {
        const res = shape[key].safeParse(v[key]);
        if (!res.success) return res;
        data[key] = res.data;
      }
      return { success: true, data };
    }),
  };
}

/**
 * Windows application identifier validator (WGn from module 1094)
 * Validates .exe filenames/paths, process: prefixes, UWP AUMID packages, and AutoGenerated classes
 */
export function isWindowsAppIdentifier(id) {
  if (typeof id !== "string") return false;
  const t = id.trim();
  return (
    /^[a-z][A-Za-z0-9-]*(?:\.[A-Za-z0-9-]+)+$/.test(t) || // Bundle identifier
    /^process:/i.test(t) ||                                // process:notepad.exe
    /(^|[\\/])[^\\/]+\.exe$/i.test(t) ||                   // C:\Windows\notepad.exe
    /[A-Za-z0-9][A-Za-z0-9.-]*_[A-Za-z0-9]+![A-Za-z0-9.-]+/.test(t) || // UWP / AUMID
    /(^|[.}])[^\\/!.}]+\.exe(?:\.|$)/i.test(t) ||
    /^Microsoft\.AutoGenerated\.\{[0-9A-F-]+\}$/i.test(t)  // Auto-generated window class
  );
}

// Clean and normalize strings
const cleanString = z
  .string()
  .transform((val) => val.replace(/\s+/g, " ").trim())
  .pipe(z.string().min(1).max(120));

const optionalCleanString = cleanString.optional().catch(undefined);

const MAX_DETAIL_LENGTH = 48;
const detailString = z
  .string()
  .transform((val) => {
    const trimmed = val.replace(/\s+/g, " ").trim();
    return trimmed.length <= MAX_DETAIL_LENGTH ? trimmed : `${trimmed.slice(0, MAX_DETAIL_LENGTH).trimEnd()}…`;
  })
  .pipe(z.string().min(1))
  .optional()
  .catch(undefined);

const textInputString = z
  .string()
  .min(1)
  .catch(undefined);

export const DirectionSchema = z
  .string()
  .transform((val) => val.trim().toLowerCase())
  .pipe(z.enum(["up", "down", "left", "right"]))
  .optional()
  .catch(undefined);

export const MouseButtonSchema = z
  .enum(["left", "right", "middle", "l", "r", "m"])
  .default("left");

export const PointSchema = z.tuple([z.number(), z.number()]);

export const ActionTargetSchema = z.union([
  z.number().int().nonnegative(),
  PointSchema,
]);

export const AppDescriptorSchema = z
  .object({
    appName: optionalCleanString,
    app_name: optionalCleanString,
    bundleId: optionalCleanString,
    bundle_id: optionalCleanString,
    bundleIdentifier: optionalCleanString,
    bundle_identifier: optionalCleanString,
    displayName: optionalCleanString,
    display_name: optionalCleanString,
    name: optionalCleanString,
    title: optionalCleanString,
  })
  .passthrough();

export const AppTargetSchema = z
  .union([cleanString, AppDescriptorSchema])
  .optional()
  .catch(undefined);

// 1. Click Tool
export const ClickToolSchema = z.object({
  target: ActionTargetSchema.optional().describe("Target element index or [x, y] coordinate pair"),
  coordinates: ActionTargetSchema.optional(),
  point: ActionTargetSchema.optional(),
  element_index: z.number().int().nonnegative().optional(),
  mouse_button: MouseButtonSchema.optional().describe("Mouse button: left, right, middle"),
  click_count: z.number().int().positive().default(1).describe("Number of clicks (1 for single, 2 for double)"),
  app: AppTargetSchema.describe("Target Windows app: process:app.exe, .exe path, UWP AUMID, or descriptor"),
}).transform((data) => ({
  ...data,
  target: data.target ?? data.coordinates ?? data.point,
})).passthrough();

// 2. Drag Tool
export const DragToolSchema = z.object({
  from: PointSchema.describe("Starting [x, y] coordinate"),
  to: PointSchema.describe("Ending [x, y] coordinate"),
  app: AppTargetSchema.describe("Target Windows application identifier"),
}).passthrough();

// 3. Scroll Tool
export const ScrollToolSchema = z.object({
  target: ActionTargetSchema.optional().describe("Element index or coordinate where scroll should occur"),
  coordinates: ActionTargetSchema.optional(),
  point: ActionTargetSchema.optional(),
  element_index: z.number().int().nonnegative().optional(),
  direction: DirectionSchema.describe("Scroll direction: up, down, left, right"),
  pages: z.number().positive().optional().default(1).describe("Number of pages or steps to scroll"),
  app: AppTargetSchema.describe("Target Windows application identifier"),
}).passthrough();

// 4. Type Text Tool
export const TypeTextToolSchema = z.object({
  text: textInputString.optional().describe("Text to type into the focused input"),
  value: textInputString.optional(),
  string: textInputString.optional(),
  target: ActionTargetSchema.optional().describe("Optional element index or position to click before typing"),
  coordinates: ActionTargetSchema.optional(),
  point: ActionTargetSchema.optional(),
  element_index: z.number().int().nonnegative().optional(),
  app: AppTargetSchema.describe("Target Windows application identifier"),
}).transform((data) => ({
  ...data,
  text: data.text ?? data.value ?? data.string ?? "",
})).passthrough();

// 5. Press Key Tool
export const PressKeyToolSchema = z.object({
  key: z.string().min(1).optional().describe("Key name or Windows shortcut (e.g. Return, Tab, ctrl+c, ctrl+v, alt+f4)"),
  shortcut: z.string().optional(),
  keys: z.string().optional(),
  app: AppTargetSchema.describe("Target Windows application identifier"),
}).transform((data) => ({
  ...data,
  key: data.key ?? data.shortcut ?? data.keys ?? "Return",
})).passthrough();

// 6. Set Value Tool (Direct Windows UI Automation Value Assignment)
export const SetValueToolSchema = z.object({
  element_index: z.number().int().nonnegative().optional().describe("Target element index in the UIA accessibility tree"),
  target: ActionTargetSchema.optional(),
  value: textInputString.describe("Value to assign to the element"),
  targetValue: textInputString.optional(),
  target_value: textInputString.optional(),
  app: AppTargetSchema.describe("Target Windows application identifier"),
}).passthrough();

// 7. Get App State Tool (Observation via Windows Capture Bridge & UIA)
export const GetAppStateToolSchema = z.object({
  app: AppTargetSchema.describe("Target Windows application identifier"),
  content: z.enum(["axState", "screenshot", "axStateAndScreenshot"]).default("axStateAndScreenshot").describe("Content to observe"),
  disable_diffing: z.boolean().optional().describe("Disable state delta optimization"),
}).passthrough();

// 8. List Apps Tool (Windows Desktop & UIA Applications)
export const ListAppsToolSchema = z.object({
  include_hidden: z.boolean().optional().default(false),
}).passthrough();

// 9. Perform Accessibility Action Tool (Windows UIA Pattern Invocations)
export const PerformAccessibilityActionToolSchema = z.object({
  element_index: z.number().int().nonnegative().optional().describe("UIA Accessibility element index"),
  target: ActionTargetSchema.optional(),
  action: z.string().min(1).optional().default("invoke").describe("Action pattern to trigger (e.g. Invoke, Expand, Select)"),
  app: AppTargetSchema.describe("Target Windows application identifier"),
}).passthrough();

// 10. Appshot Capture Tool (Windows Desktop Window Snapping Bridge)
export const AppshotCaptureToolSchema = z.object({
  window: z.object({
    app: z.string().describe("Executable or process name"),
    id: z.union([z.number().int().nonnegative(), z.string()]).describe("HWND or window ID"),
    title: z.string().optional(),
    frame: z.object({
      x: z.number(),
      y: z.number(),
      width: z.number().positive(),
      height: z.number().positive(),
    }).optional(),
  }),
  animationTarget: z.any().optional(),
  transitionId: z.string().optional(),
}).passthrough();
